 name: Build and push Cuda RTX 4000 series docker image to registry

 on:
   workflow_dispatch:
   push:
     branches:
       - 'main'
     tags:
       - 'v*'

 jobs:
   build-and-push-image:
     concurrency:
       group: ${{ github.workflow }}-${{ github.job }}-89-${{ github.head_ref || github.run_id }}
       cancel-in-progress: true
     runs-on: [self-hosted, intel-cpu, 32-cpu, 256-ram, ci]
     permissions:
       contents: write
       packages: write
       # This is used to complete the identity challenge
       # with sigstore/fulcio when running outside of PRs.
       id-token: write
       security-events: write
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Initialize Docker Buildx
         uses: docker/setup-buildx-action@v2.0.0
         with:
           install: true
           config-inline: |
             [registry."docker.io"]
               mirrors = ["registry.github-runners.huggingface.tech"]

       - name: Configure sccache
         uses: actions/github-script@v6
         with:
           script: |
             core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
             core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

       - name: Inject slug/short variables
         uses: rlespinasse/github-slug-action@v4.4.1

       - name: Login to GitHub Container Registry
         if: github.event_name != 'pull_request'
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

       - name: Extract metadata (tags, labels) for Docker
         id: meta-89
         uses: docker/metadata-action@v4.3.0
         with:
           images: |
             registry-push.github-runners.huggingface.tech/api-inference/text-embeddings-inference
             ghcr.io/huggingface/text-embeddings-inference
           flavor: |
             latest=false
           tags: |
             type=semver,pattern=89-{{version}}
             type=semver,pattern=89-{{major}}.{{minor}}
             type=raw,value=89-latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
             type=raw,value=89-sha-${{ env.GITHUB_SHA_SHORT }}

       - name: Build and push Docker image
         id: build-and-push-89
         uses: docker/build-push-action@v4
         with:
           context: .
           file: Dockerfile-cuda
           push: ${{ github.event_name != 'pull_request' }}
           platforms: 'linux/amd64'
           build-args: |
             SCCACHE_GHA_ENABLED=on
             ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
             ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
             CUDA_COMPUTE_CAP=89
             GIT_SHA=${{ env.GITHUB_SHA }}
             DOCKER_LABEL=sha-${{ env.GITHUB_SHA_SHORT }}
           tags: ${{ steps.meta-89.outputs.tags }}
           labels: ${{ steps.meta-89.outputs.labels }}
           cache-from: type=s3,region=us-east-1,bucket=ci-docker-buildx-cache,name=text-embeddings-inference-cache-89,access_key_id=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_ACCESS_KEY_ID }},secret_access_key=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_SECRET_ACCESS_KEY }},mode=max
           cache-to: type=s3,region=us-east-1,bucket=ci-docker-buildx-cache,name=text-embeddings-inference-cache-89,access_key_id=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_ACCESS_KEY_ID }},secret_access_key=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_SECRET_ACCESS_KEY }},mode=max

       - name: Extract metadata (tags, labels) for Docker
         id: meta-89-grpc
         uses: docker/metadata-action@v4.3.0
         with:
           images: |
             registry-push.github-runners.huggingface.tech/api-inference/text-embeddings-inference
             ghcr.io/huggingface/text-embeddings-inference
           flavor: |
             latest=false
           tags: |
             type=semver,pattern=89-{{version}}-grpc
             type=semver,pattern=89-{{major}}.{{minor}}-grpc
             type=raw,value=89-latest-grpc
             type=raw,value=89-sha-${{ env.GITHUB_SHA_SHORT }}-grpc

       - name: Build and push Docker image
         id: build-and-push-89-grpc
         uses: docker/build-push-action@v4
         with:
           context: .
           target: grpc
           file: Dockerfile-cuda
           push: ${{ github.event_name != 'pull_request' }}
           platforms: 'linux/amd64'
           build-args: |
             SCCACHE_GHA_ENABLED=on
             ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
             ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
             CUDA_COMPUTE_CAP=89
             GIT_SHA=${{ env.GITHUB_SHA }}
             DOCKER_LABEL=sha-${{ env.GITHUB_SHA_SHORT }}
           tags: ${{ steps.meta-89-grpc.outputs.tags }}
           labels: ${{ steps.meta-89-grpc.outputs.labels }}
           cache-from: type=s3,region=us-east-1,bucket=ci-docker-buildx-cache,name=text-embeddings-inference-cache-89,access_key_id=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_ACCESS_KEY_ID }},secret_access_key=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_SECRET_ACCESS_KEY }},mode=max
