name: Run basic tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - ".github/workflows/build.yaml"
      - ".github/workflows/matrix.json"
      - "integration-tests/**"
      - "backends/**"
      - "core/**"
      - "router/**"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "Dockerfile"
    branches:
      - 'main'

jobs:
  tests:
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    runs-on:
      group: aws-highmemory-32-plus-priv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Compile project
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: |
          sudo apt-get update && sudo apt-get install protobuf-compiler -y
          cargo test --profile=release-debug
